// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: transaction/v1/transaction.proto

package transactionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDealRequest) Reset() {
	*x = GetDealRequest{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDealRequest) ProtoMessage() {}

func (x *GetDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDealRequest.ProtoReflect.Descriptor instead.
func (*GetDealRequest) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *GetDealRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

type DealResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DealId    string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	OfferId   string                 `protobuf:"bytes,2,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	ListingId string                 `protobuf:"bytes,3,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	BuyerId   string                 `protobuf:"bytes,4,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId  string                 `protobuf:"bytes,5,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	// Decimal amount transported as a string to avoid float precision loss.
	AgreedAmount  string                 `protobuf:"bytes,6,opt,name=agreed_amount,json=agreedAmount,proto3" json:"agreed_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealResponse) Reset() {
	*x = DealResponse{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealResponse) ProtoMessage() {}

func (x *DealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealResponse.ProtoReflect.Descriptor instead.
func (*DealResponse) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *DealResponse) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

func (x *DealResponse) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *DealResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *DealResponse) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *DealResponse) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *DealResponse) GetAgreedAmount() string {
	if x != nil {
		return x.AgreedAmount
	}
	return ""
}

func (x *DealResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DealResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DealResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DealResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *DealResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type WalletResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WalletId string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId   string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Decimal balance transported as a string to avoid float precision loss.
	Balance       string                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *WalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WalletResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *WalletResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WalletResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WalletResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_transaction_v1_transaction_proto protoreflect.FileDescriptor

const file_transaction_v1_transaction_proto_rawDesc = "" +
	"\n" +
	" transaction/v1/transaction.proto\x12\x0etransaction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x0eGetDealRequest\x12\x17\n" +
	"\adeal_id\x18\x01 \x01(\tR\x06dealId\"\xab\x03\n" +
	"\fDealResponse\x12\x17\n" +
	"\adeal_id\x18\x01 \x01(\tR\x06dealId\x12\x19\n" +
	"\boffer_id\x18\x02 \x01(\tR\aofferId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x03 \x01(\tR\tlistingId\x12\x19\n" +
	"\bbuyer_id\x18\x04 \x01(\tR\abuyerId\x12\x1b\n" +
	"\tseller_id\x18\x05 \x01(\tR\bsellerId\x12#\n" +
	"\ragreed_amount\x18\x06 \x01(\tR\fagreedAmount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12=\n" +
	"\fcancelled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\x8a\x02\n" +
	"\x0eWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xac\x01\n" +
	"\x12TransactionService\x12G\n" +
	"\aGetDeal\x12\x1e.transaction.v1.GetDealRequest\x1a\x1c.transaction.v1.DealResponse\x12M\n" +
	"\tGetWallet\x12 .transaction.v1.GetWalletRequest\x1a\x1e.transaction.v1.WalletResponseBDZBnotification-service/internal/grpcgen/transaction/v1;transactionv1b\x06proto3"

var (
	file_transaction_v1_transaction_proto_rawDescOnce sync.Once
	file_transaction_v1_transaction_proto_rawDescData []byte
)

func file_transaction_v1_transaction_proto_rawDescGZIP() []byte {
	file_transaction_v1_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_v1_transaction_proto_rawDesc), len(file_transaction_v1_transaction_proto_rawDesc)))
	})
	return file_transaction_v1_transaction_proto_rawDescData
}

var file_transaction_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_v1_transaction_proto_goTypes = []any{
	(*GetDealRequest)(nil),        // 0: transaction.v1.GetDealRequest
	(*DealResponse)(nil),          // 1: transaction.v1.DealResponse
	(*GetWalletRequest)(nil),      // 2: transaction.v1.GetWalletRequest
	(*WalletResponse)(nil),        // 3: transaction.v1.WalletResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_transaction_v1_transaction_proto_depIdxs = []int32{
	4, // 0: transaction.v1.DealResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: transaction.v1.DealResponse.completed_at:type_name -> google.protobuf.Timestamp
	4, // 2: transaction.v1.DealResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	4, // 3: transaction.v1.WalletResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: transaction.v1.WalletResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: transaction.v1.TransactionService.GetDeal:input_type -> transaction.v1.GetDealRequest
	2, // 6: transaction.v1.TransactionService.GetWallet:input_type -> transaction.v1.GetWalletRequest
	1, // 7: transaction.v1.TransactionService.GetDeal:output_type -> transaction.v1.DealResponse
	3, // 8: transaction.v1.TransactionService.GetWallet:output_type -> transaction.v1.WalletResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_transaction_v1_transaction_proto_init() }
func file_transaction_v1_transaction_proto_init() {
	if File_transaction_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_v1_transaction_proto_rawDesc), len(file_transaction_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_v1_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_v1_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_v1_transaction_proto_msgTypes,
	}.Build()
	File_transaction_v1_transaction_proto = out.File
	file_transaction_v1_transaction_proto_goTypes = nil
	file_transaction_v1_transaction_proto_depIdxs = nil
}
