// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: messaging/v1/messaging.proto

package messagingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_messaging_v1_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_v1_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_messaging_v1_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_messaging_v1_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_v1_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_messaging_v1_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *Participant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Participant) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LastMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ContentPreview string                 `protobuf:"bytes,3,opt,name=content_preview,json=contentPreview,proto3" json:"content_preview,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LastMessage) Reset() {
	*x = LastMessage{}
	mi := &file_messaging_v1_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastMessage) ProtoMessage() {}

func (x *LastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_v1_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastMessage.ProtoReflect.Descriptor instead.
func (*LastMessage) Descriptor() ([]byte, []int) {
	return file_messaging_v1_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *LastMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *LastMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *LastMessage) GetContentPreview() string {
	if x != nil {
		return x.ContentPreview
	}
	return ""
}

func (x *LastMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type ConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Participants   []*Participant         `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	ListingId      string                 `protobuf:"bytes,3,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	LastMessage    *LastMessage           `protobuf:"bytes,4,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationResponse) Reset() {
	*x = ConversationResponse{}
	mi := &file_messaging_v1_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationResponse) ProtoMessage() {}

func (x *ConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_v1_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationResponse.ProtoReflect.Descriptor instead.
func (*ConversationResponse) Descriptor() ([]byte, []int) {
	return file_messaging_v1_messaging_proto_rawDescGZIP(), []int{3}
}

func (x *ConversationResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *ConversationResponse) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *ConversationResponse) GetLastMessage() *LastMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *ConversationResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConversationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_messaging_v1_messaging_proto protoreflect.FileDescriptor

const file_messaging_v1_messaging_proto_rawDesc = "" +
	"\n" +
	"\x1cmessaging/v1/messaging.proto\x12\fmessaging.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\":\n" +
	"\vParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xa7\x01\n" +
	"\vLastMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12'\n" +
	"\x0fcontent_preview\x18\x03 \x01(\tR\x0econtentPreview\x123\n" +
	"\asent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xd1\x02\n" +
	"\x14ConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12=\n" +
	"\fparticipants\x18\x02 \x03(\v2\x19.messaging.v1.ParticipantR\fparticipants\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x03 \x01(\tR\tlistingId\x12<\n" +
	"\flast_message\x18\x04 \x01(\v2\x19.messaging.v1.LastMessageR\vlastMessage\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2o\n" +
	"\x10MessagingService\x12[\n" +
	"\x0fGetConversation\x12$.messaging.v1.GetConversationRequest\x1a\".messaging.v1.ConversationResponseB@Z>notification-service/internal/grpcgen/messaging/v1;messagingv1b\x06proto3"

var (
	file_messaging_v1_messaging_proto_rawDescOnce sync.Once
	file_messaging_v1_messaging_proto_rawDescData []byte
)

func file_messaging_v1_messaging_proto_rawDescGZIP() []byte {
	file_messaging_v1_messaging_proto_rawDescOnce.Do(func() {
		file_messaging_v1_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messaging_v1_messaging_proto_rawDesc), len(file_messaging_v1_messaging_proto_rawDesc)))
	})
	return file_messaging_v1_messaging_proto_rawDescData
}

var file_messaging_v1_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messaging_v1_messaging_proto_goTypes = []any{
	(*GetConversationRequest)(nil), // 0: messaging.v1.GetConversationRequest
	(*Participant)(nil),            // 1: messaging.v1.Participant
	(*LastMessage)(nil),            // 2: messaging.v1.LastMessage
	(*ConversationResponse)(nil),   // 3: messaging.v1.ConversationResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_messaging_v1_messaging_proto_depIdxs = []int32{
	4, // 0: messaging.v1.LastMessage.sent_at:type_name -> google.protobuf.Timestamp
	1, // 1: messaging.v1.ConversationResponse.participants:type_name -> messaging.v1.Participant
	2, // 2: messaging.v1.ConversationResponse.last_message:type_name -> messaging.v1.LastMessage
	4, // 3: messaging.v1.ConversationResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: messaging.v1.ConversationResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: messaging.v1.MessagingService.GetConversation:input_type -> messaging.v1.GetConversationRequest
	3, // 6: messaging.v1.MessagingService.GetConversation:output_type -> messaging.v1.ConversationResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_messaging_v1_messaging_proto_init() }
func file_messaging_v1_messaging_proto_init() {
	if File_messaging_v1_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messaging_v1_messaging_proto_rawDesc), len(file_messaging_v1_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messaging_v1_messaging_proto_goTypes,
		DependencyIndexes: file_messaging_v1_messaging_proto_depIdxs,
		MessageInfos:      file_messaging_v1_messaging_proto_msgTypes,
	}.Build()
	File_messaging_v1_messaging_proto = out.File
	file_messaging_v1_messaging_proto_goTypes = nil
	file_messaging_v1_messaging_proto_depIdxs = nil
}
