# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messaging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\x12\x0cmessaging.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n\x16GetConversationRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\",\n\x0bParticipant\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"z\n\x0bLastMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63ontent_preview\x18\x03 \x01(\t\x12+\n\x07sent_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x85\x02\n\x14\x43onversationResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12/\n\x0cparticipants\x18\x02 \x03(\x0b\x32\x19.messaging.v1.Participant\x12\x12\n\nlisting_id\x18\x03 \x01(\t\x12/\n\x0clast_message\x18\x04 \x01(\x0b\x32\x19.messaging.v1.LastMessage\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2o\n\x10MessagingService\x12[\n\x0fGetConversation\x12$.messaging.v1.GetConversationRequest\x1a\".messaging.v1.ConversationResponseB@Z>notification-service/internal/grpcgen/messaging/v1;messagingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>notification-service/internal/grpcgen/messaging/v1;messagingv1'
  _globals['_GETCONVERSATIONREQUEST']._serialized_start=66
  _globals['_GETCONVERSATIONREQUEST']._serialized_end=115
  _globals['_PARTICIPANT']._serialized_start=117
  _globals['_PARTICIPANT']._serialized_end=161
  _globals['_LASTMESSAGE']._serialized_start=163
  _globals['_LASTMESSAGE']._serialized_end=285
  _globals['_CONVERSATIONRESPONSE']._serialized_start=288
  _globals['_CONVERSATIONRESPONSE']._serialized_end=549
  _globals['_MESSAGINGSERVICE']._serialized_start=551
  _globals['_MESSAGINGSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
