# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n\tEntityRef\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"\xa7\x01\n\x19\x43reateNotificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x15\n\x08\x61\x63tor_id\x18\x05 \x01(\tH\x00\x88\x01\x01\x12*\n\x06\x65ntity\x18\x06 \x01(\x0b\x32\x1a.notification.v1.EntityRefB\x0b\n\t_actor_id\"\x82\x02\n\x1a\x43reateNotificationResponse\x12\x17\n\x0fnotification_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x15\n\x08\x61\x63tor_id\x18\x06 \x01(\tH\x00\x88\x01\x01\x12*\n\x06\x65ntity\x18\x07 \x01(\x0b\x32\x1a.notification.v1.EntityRef\x12\x0f\n\x07is_read\x18\x08 \x01(\x08\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0b\n\t_actor_id2\x84\x01\n\x13NotificationService\x12m\n\x12\x43reateNotification\x12*.notification.v1.CreateNotificationRequest\x1a+.notification.v1.CreateNotificationResponseBFZDnotification-service/internal/grpcgen/notification/v1;notificationv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDnotification-service/internal/grpcgen/notification/v1;notificationv1'
  _globals['_ENTITYREF']._serialized_start=72
  _globals['_ENTITYREF']._serialized_end=109
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_start=112
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_end=279
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_start=282
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_end=540
  _globals['_NOTIFICATIONSERVICE']._serialized_start=543
  _globals['_NOTIFICATIONSERVICE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
