# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0etransaction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n\x0eGetDealRequest\x12\x0f\n\x07\x64\x65\x61l_id\x18\x01 \x01(\t\"\xb7\x02\n\x0c\x44\x65\x61lResponse\x12\x0f\n\x07\x64\x65\x61l_id\x18\x01 \x01(\t\x12\x10\n\x08offer_id\x18\x02 \x01(\t\x12\x12\n\nlisting_id\x18\x03 \x01(\t\x12\x10\n\x08\x62uyer_id\x18\x04 \x01(\t\x12\x11\n\tseller_id\x18\x05 \x01(\t\x12\x15\n\ragreed_amount\x18\x06 \x01(\t\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x63ompleted_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x63\x61ncelled_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"%\n\x10GetWalletRequest\x12\x11\n\twallet_id\x18\x01 \x01(\t\"\xc7\x01\n\x0eWalletResponse\x12\x11\n\twallet_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\t\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xac\x01\n\x12TransactionService\x12G\n\x07GetDeal\x12\x1e.transaction.v1.GetDealRequest\x1a\x1c.transaction.v1.DealResponse\x12M\n\tGetWallet\x12 .transaction.v1.GetWalletRequest\x1a\x1e.transaction.v1.WalletResponseBDZBnotification-service/internal/grpcgen/transaction/v1;transactionv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBnotification-service/internal/grpcgen/transaction/v1;transactionv1'
  _globals['_GETDEALREQUEST']._serialized_start=70
  _globals['_GETDEALREQUEST']._serialized_end=103
  _globals['_DEALRESPONSE']._serialized_start=106
  _globals['_DEALRESPONSE']._serialized_end=417
  _globals['_GETWALLETREQUEST']._serialized_start=419
  _globals['_GETWALLETREQUEST']._serialized_end=456
  _globals['_WALLETRESPONSE']._serialized_start=459
  _globals['_WALLETRESPONSE']._serialized_end=658
  _globals['_TRANSACTIONSERVICE']._serialized_start=661
  _globals['_TRANSACTIONSERVICE']._serialized_end=833
# @@protoc_insertion_point(module_scope)
