# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transaction_pb2 as transaction__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transaction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionServiceStub(object):
    """Thin 1:1 mirrors of already-tested REST behavior (DealsController.Get, WalletsController.GetMine).
    Exposed for future gRPC consumers; no caller wires this yet in this pass.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeal = channel.unary_unary(
                '/transaction.v1.TransactionService/GetDeal',
                request_serializer=transaction__pb2.GetDealRequest.SerializeToString,
                response_deserializer=transaction__pb2.DealResponse.FromString,
                _registered_method=True)
        self.GetWallet = channel.unary_unary(
                '/transaction.v1.TransactionService/GetWallet',
                request_serializer=transaction__pb2.GetWalletRequest.SerializeToString,
                response_deserializer=transaction__pb2.WalletResponse.FromString,
                _registered_method=True)


class TransactionServiceServicer(object):
    """Thin 1:1 mirrors of already-tested REST behavior (DealsController.Get, WalletsController.GetMine).
    Exposed for future gRPC consumers; no caller wires this yet in this pass.
    """

    def GetDeal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeal,
                    request_deserializer=transaction__pb2.GetDealRequest.FromString,
                    response_serializer=transaction__pb2.DealResponse.SerializeToString,
            ),
            'GetWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallet,
                    request_deserializer=transaction__pb2.GetWalletRequest.FromString,
                    response_serializer=transaction__pb2.WalletResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction.v1.TransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transaction.v1.TransactionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionService(object):
    """Thin 1:1 mirrors of already-tested REST behavior (DealsController.Get, WalletsController.GetMine).
    Exposed for future gRPC consumers; no caller wires this yet in this pass.
    """

    @staticmethod
    def GetDeal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.v1.TransactionService/GetDeal',
            transaction__pb2.GetDealRequest.SerializeToString,
            transaction__pb2.DealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction.v1.TransactionService/GetWallet',
            transaction__pb2.GetWalletRequest.SerializeToString,
            transaction__pb2.WalletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
