-- Marketplace DB, per Artifacts/circular-economy-marketplace-eerds.pdf (EERD 2) and
-- services/marketplace-service/EERD.md. VENDOR, CORPORATE, CATEGORY, LOCATION, LISTING,
-- LISTING_MEDIA, VENDOR_CORPORATE_RELATIONSHIP were applied directly via Supabase MCP ahead of
-- this service's code (same precedent as transaction_db.offer/deal -- see
-- services/transaction-service/db/migrations/0001_create_wallet_tables.sql's own header comment).
-- This file checks that already-applied schema into the repo, matching the base EERD field set
-- exactly (no marketplace-service-specific extensions here -- see 0002 for those).

CREATE SCHEMA IF NOT EXISTS marketplace_db;

CREATE TABLE marketplace_db.vendor (
    vendor_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL UNIQUE,
    vendor_name varchar(150) NOT NULL,
    description text NULL,
    business_registration_number varchar(50) NULL UNIQUE,
    verification_status varchar(16) NOT NULL DEFAULT 'UNVERIFIED' CHECK (verification_status IN ('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED')),
    verified_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN marketplace_db.vendor.user_id IS 'EXT external reference to Auth Service USER.user_id - no physical FK, no cross-database constraint';

CREATE TABLE marketplace_db.corporate (
    corporate_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL UNIQUE,
    company_name varchar(150) NOT NULL,
    description text NULL,
    business_registration_number varchar(50) NULL UNIQUE,
    industry varchar(100) NULL,
    website varchar(255) NULL,
    verification_status varchar(16) NOT NULL DEFAULT 'UNVERIFIED' CHECK (verification_status IN ('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED')),
    verified_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN marketplace_db.corporate.user_id IS 'EXT external reference to Auth Service USER.user_id - no physical FK, no cross-database constraint';

CREATE TABLE marketplace_db.category (
    category_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(255) NULL,
    parent_category_id smallint NULL REFERENCES marketplace_db.category (category_id)
);

COMMENT ON TABLE marketplace_db.category IS 'Recursive 1:N hierarchy of unlimited depth, e.g. Waste > Plastic > PET > PET Bottles. Root category: parent_category_id IS NULL';

CREATE TABLE marketplace_db.location (
    location_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    country char(2) NOT NULL,
    city varchar(100) NOT NULL,
    address varchar(255) NULL,
    latitude numeric(9,6) NULL,
    longitude numeric(9,6) NULL
);

COMMENT ON COLUMN marketplace_db.location.country IS 'ISO 3166-1 alpha-2';

CREATE TABLE marketplace_db.listing (
    listing_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id uuid NOT NULL,
    title varchar(200) NOT NULL,
    description text NULL,
    category_id smallint NOT NULL REFERENCES marketplace_db.category (category_id),
    condition varchar(16) NOT NULL CHECK (condition IN ('NEW', 'USED', 'REFURBISHED', 'SCRAP', 'MIXED')),
    quantity numeric(12,3) NOT NULL CHECK (quantity > 0),
    unit varchar(10) NOT NULL CHECK (unit IN ('KG', 'TONNE', 'UNIT', 'PALLET', 'M3', 'LITRE')),
    expected_amount numeric(14,2) NULL,
    currency char(3) NULL,
    location_id uuid NULL REFERENCES marketplace_db.location (location_id),
    status varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RESERVED', 'SOLD', 'COMPLETED', 'CANCELLED', 'EXPIRED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN marketplace_db.listing.owner_id IS 'EXT external reference - logical: owner_id = Auth Service USER.user_id (vendor or corporate account)';

CREATE INDEX idx_listing_owner ON marketplace_db.listing (owner_id);
CREATE INDEX idx_listing_status ON marketplace_db.listing (status);
CREATE INDEX idx_listing_category ON marketplace_db.listing (category_id);

CREATE TABLE marketplace_db.listing_media (
    media_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id uuid NOT NULL REFERENCES marketplace_db.listing (listing_id),
    url varchar(500) NOT NULL,
    media_type varchar(10) NOT NULL CHECK (media_type IN ('IMAGE', 'DOCUMENT')),
    sort_order smallint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE marketplace_db.listing_media IS 'Photos and waste-transfer documents';

CREATE TABLE marketplace_db.vendor_corporate_relationship (
    relationship_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor_id uuid NOT NULL REFERENCES marketplace_db.vendor (vendor_id),
    corporate_id uuid NOT NULL REFERENCES marketplace_db.corporate (corporate_id),
    status varchar(16) NOT NULL CHECK (status IN ('REQUESTED', 'ACTIVE', 'BLOCKED', 'ENDED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (vendor_id, corporate_id)
);

COMMENT ON TABLE marketplace_db.vendor_corporate_relationship IS 'Associative entity resolving VENDOR M:N CORPORATE';

ALTER TABLE marketplace_db.vendor ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_db.corporate ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_db.category ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_db.location ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_db.listing ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_db.listing_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_db.vendor_corporate_relationship ENABLE ROW LEVEL SECURITY;
